spring:
  application:
    name: bank-cards
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/main_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yml
    enabled: true

server:
  port: ${SERVER_PORT:8080}

app:
  security:
    jwt:
      issuer: bank-cards
      secret: ${JWT_SECRET:secretsecret}
      access-token-ttl: ${JWT_ACCESS_TTL:PT15M}
      refresh-token-ttl: ${JWT_REFRESH_TTL:P7D}
      header: Authorization
      prefix: "Bearer "
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
